# Disable due is now integrated on travis

stages:
  - build
  - clean

.template: &template
  tags:
    - ch-docker-dood

.template_build: &template_build
  <<: *template
  stage: build
  artifacts:
    name: reports
    when: always
    expire_in: 1 day
    paths:
      - builds

build:5.2:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 5.2

build:5.3:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 5.3

build:5.4:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 5.4

build:5.5:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 5.5

build:5.6:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 5.6

build:7.0:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 7.0

build:7.1:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 7.1

build:7.2:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 7.2

build:7.3:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 7.3

build:7.4:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 7.4

build:8.0:
  <<: *template_build
  script:
    - ./gitlab-ci.sh 8.0

clean:hard:
  <<: *template
  stage: clean
  when: manual
  script:
    - docker system prune --all --volumes --force
