stages:
  - check
  - build
  - push
  - clean

.template: &template
  tags:
    - docker-dood

.template_build: &template_build
  <<: *template
  stage: build
  artifacts:
    name: reports
    when: on_success
    expire_in: 1 day
    paths:
      - builds/

check:modifications:
  <<: *template
  stage: check
  script:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${CI_BUILD_REF}~..${CI_BUILD_REF}")); unset IFS
    - echo "COMMIT_SCA_FILES='${COMMIT_SCA_FILES}'"
    - [[ "${COMMIT_SCA_FILES}" =~ setup/ ]]

build:52:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.2

build:53:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.3

build:54:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.4

build:55:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.5

build:56:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.6

build:70:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.0

build:71:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.1

build:72:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.2

push:nothing:
  <<: *template
  stage: push

push:dev:
  <<: *template
  stage: push
  when: manual
  script:
    - ./docker-build.sh all

push:all:
  <<: *template
  stage: push
  only: 
    - master
  when: manual
  script:
    - ./docker-build.sh all
    - ./docker-push.sh all

clean:nothing:
  <<: *template
  stage: clean

clean:soft:
  <<: *template
  stage: clean
  when: manual
  script:
    - docker system prune --volumes --force

clean:hard:
  <<: *template
  stage: clean
  when: manual
  script:
    - docker system prune --all --volumes --force