stages:
  - build
  - push
  - clean

.template: &template
  tags:
    - docker-dood

.template_build: &template_build
  <<: *template
  stage: build
  artifacts:
    name: reports
    when: on_success
    expire_in: 1 day
    paths:
      - builds/

build:52:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.2

build:53:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.3

build:54:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.4

build:55:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.5

build:56:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 5.6

build:70:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.0

build:71:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.1

build:72:
  <<: *template_build
  script:
    - di_disable_push=1 ./docker-build.sh 7.2

push:all:
  <<: *template
  stage: push
  only: master
  when: manual
  script:
    - ./docker-push.sh all

clean:soft:
  <<: *template
  when: manual
  script:
    - docker system prune --volumes --force

clean:hard:
  <<: *template
  when: manual
  script:
    - docker system prune --all --volumes --force