dist: jessie
sudo: required
language: php
services:
  - docker

env:
  - PHP_VERSION=5.2
  - PHP_VERSION=5.3
  - PHP_VERSION=5.4
  - PHP_VERSION=5.5
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
  - PHP_VERSION=7.2

#stages:
#  - compile
#  - name: deploy
#    if: branch = master

matrix:
  allow_failures:
    - PHP_VERSION=5.2
    - PHP_VERSION=5.3

script: ./docker-build.sh $PHP_VERSION

#- stage: deploy
#  script:
#    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
#    - ./docker-push.sh $PHP_VERSION
