sudo: required
services:
  - docker

env:
  - PHP=5.2
  - PHP=5.3
  - PHP=5.4
  - PHP=5.5
  - PHP=5.6
  - PHP=7.0
  - PHP=7.1
  - PHP=7.2

matrix:
  allow_failures:
    - PHP=5.2
    - PHP=5.3

script:
  - ./travis $PHP
