version: "3.7"
services:
  web:
    image: virtuasa/php:8.1-v2 # @todo select your php version
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    environment:
      # @todo: change the following value accordingly to your project settings
      - APACHE_DOCUMENT_ROOT=web
      - APACHE_LOG_PATH=var/logs/apache
      - DOCKER_COPY_CONFIG_FROM_HOST=false
      - DOCKER_COPY_CONFIG_TO_HOST=false
      - DOCKER_HOST_SETUP_DIR=setup
      - DOCKER_TIMEZONE=Europe/Zurich
      - PHP_LOG_PATH=var/logs
      - HISTFILE=/data/.docker_bash_history
      - HISTFILESIZE=1000
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-}
      #GLILAB-CI:- COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR:-}
      #GLILAB-CI:- YARN_CACHE_FOLDER=${YARN_CACHE_FOLDER:-}
      #GLILAB-CI:- NPM_CONFIG_CACHE=${NPM_CONFIG_CACHE:-}
      #GLILAB-CI:- bower_storage__packages=${bower_storage__packages:-}
    volumes:
      - ./:/data
    labels:
      # @todo: change the following value accordingly to your project name
      - "com.dnsdock.alias=web.project.customer.docker"
    # links: # @todo: add a others service linkss <image-name>:<docker-host-name>
    #   - db:db.project.customer.docker
    #   - redis:redis.project.customer.docker
    #ports: # To bind on machine IP, example for mobile testing or if no dnsdock
    #  - "80"
    #  - "443"
